version: '3.4'

services:
  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    restart: always
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: src/GoalManager.Web/Dockerfile

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql:/var/opt/mssql

volumes:
  mssql:
    driver: local


