version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql:/var/opt/mssql

  mailserver:
    image: jijiechen/papercut:latest
    container_name: ddd.papercut
    ports: # exposes port 25 internally
      - 37409:37408

  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    restart: always
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: src/GoalManager.Web/Dockerfile

volumes:
  mssql:
    driver: local


